### ISSUE TITLE
Some settings not retained on quit

### ISSUE THREAD

**Issue by clausbertels** [TheBoredTeam/boring.notch#114] opened 2024-09-22 08:06 UTC
I noticed that "Settings icon in notch" and "minimum hover duration" are reset whenever BoringNotch is quit and restarted.

MacOS Sequoia using 1.8

**Comment by richardkunkli** [comment] 2024-09-22 12:17
Hi,
Thanks for the feedback, also this is not a bug. It's on purpose, because it helps us finding and resolving bugs much easier and faster. We are preparing for a new release and enabled the restoration of user settings.

**Closed** 2024-09-22 20:16 UTC
Labels: invalid
