### ISSUE TITLE
[BUG] Media icon stuck on spotify song even after shifting to using netflix on browser

### ISSUE THREAD

**Issue by anishsghiya** [TheBoredTeam/boring.notch#197] opened 2024-11-09 19:15 UTC
**Describe the bug**
The media display is stuck on the same spotify song while I have started watching Netflix on my browser (Arc) although the media controls have shifted to the netflix content. 

**To Reproduce**
1. Play a song on spotify
2. go to your browser and open netflix (Problem is with netflix alone on Arc browser) (PS youtube seems to be working fine with Brave browser
3. play anything on netflix
4. go to the notch
5. See error

**Expected behavior**
To show the same content playing in the browser or maybe nothing? 

**Screenshots or recordings**
<img width="541" alt="Screenshot 2024-11-09 at 11 13 50 AM" src="https://github.com/user-attachments/assets/467cecd3-fb10-445e-b9c6-e204dac694a8">

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment] 2024-11-10 00:58
This will be fixed in the next update, changes are now in the `dev` branch if you want to try them out. Closing because this is a duplicate of #172

**Closed by Alexander5015** 2024-11-10 00:58 UTC
Labels: duplicate
