### ISSUE TITLE
[FEATURE] decrease the notch size of when music is played, it covers my app menus a bit which is a bit ugly, so if u could make it smaller it would be perfect

### ISSUE THREAD

**Issue by Sagebump** [TheBoredTeam/boring.notch#242] opened 2024-12-15 14:57 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment] 2024-12-16 23:29
Duplicate of #121

**Closed by Alexander5015** 2024-12-16 23:29 UTC
