### ISSUE TITLE
[BUG] Multi Monitor/switching monitors isn't consistent and may need a relaunch depending on user settings

### ISSUE THREAD

**Issue by BagpipesRbetter** [TheBoredTeam/boring.notch#227] opened 2024-11-26 01:40 UTC
# Multi Monitor/switching monitors isn't consistent and may need a relaunch depending on user settings
## Describe the bug
I use an external monitor about 50% of the time(NOT DUAL) with my Mackbook. When swapping which display is in use, I experience one of two directly adjacent problems. First, 1st When going from functioning on built-in to external, the notch appears just to the left of the center(on external). This happens every time 2nd, when going from external to built-in, the notch is gone(I think it may just be rendering off-screen (it happens less often but frequently)). To fix this problem, I have to go into settings and manually change which monitor is selected; on the 2nd problem case, I can't get to the notch to open the settings menu; I have to get there via the menu bar icon. This is where the primary problem comes in: if you don't have that icon turned on in settings, you have an unaccessible notch that requires a relaunch(on launch, it chooses the primary monitor).

This issue is very similar to #174, but I believe it may be more expansive than #174 

I believe a change to the positioning and monitor finder may fix this with minimal effort

## Expected behavior
If I had the ultimate say over the monitor switching functionality, it would have a second section for default and then choose a backup from there, but alas, I am not yet a dev. What I would expect with the way it is now is to have it snap to the main monitor, not the center, until it finds the current monitor in the settings.

## Screenshots
Note that the settings window isn't showing a selected display

![Screenshot 2024-11-25 at 6 21 56 PM](https://github.com/user-attachments/assets/ed5c0460-7635-4fa9-a600-28972b64ba42)

## Additional context
I'm using version 2.3 on macOS Sequoia 15.1.1 with a m4 max MacBook Pro

## Checks
- [x] I have tried uninstalling and reinstalling
- [x] I do not have any other notch-related programs that might be interfering installed

**Comment by Alexander5015** [comment] 2024-11-26 01:47
This is a duplicate of #219. This will be fixed when #221 is released. If you want to try out the changes, you can check out the `dev` branch. Also we are very beginner friendly if you would like to contribute, and we could help you get started if you join our discord.

**Closed by Alexander5015** 2024-11-26 01:47 UTC
