### ISSUE TITLE
[BUG] Notch randomly placed MacOS 15.1.1

### ISSUE THREAD

**Issue by ForWarZz** [TheBoredTeam/boring.notch#235] opened 2024-12-04 21:00 UTC
**Describe the bug**
Sometimes, when I'm logging to my MacBook, the notch appears completely randomly on my screen.

**To Reproduce**
1. Loggout, and logging ? (Not happening every time)

**Expected behavior**
The notch have to be on the real notch of the MacBook

**Screenshots or recordings**
![image](https://github.com/user-attachments/assets/fb0e55c3-8d3a-4600-919d-f6346a2a73ac)
The boring notch is under the real notch, and placed on the right.

**Checks**
- May be same bug than the currently opened issue with external monitor #219, if it Is, sorry for the duplicate.

**Comment by Alexander5015** [comment] 2024-12-04 21:05
Yes, this is a duplicate of #219 and is already patched in the `dev` branch if you want to build it yourself and will be included in the next release.

**Closed by Alexander5015** 2024-12-04 21:05 UTC
Labels: duplicate
