### ISSUE TITLE
[FEATURE] Connectivity notification like alcove

### ISSUE THREAD

**Issue by FormalSnake** [TheBoredTeam/boring.notch#268] opened 2024-12-28 11:24 UTC
**Is your feature request related to a problem? Please describe.**
It is more for polish, but I love seeing on my iphone's dynamic island that my Airpods have been connected. This has made me consider switching to Alcove but it is not worth 17 euro and is generally a downgrade :p

**Describe the solution you'd like**
When I connect my airpods pro when using Alcove, I get a cool 3D model of them that spins and that says they are connected, boringnotch doesn't do that at all.

**Additional context**
Demo from their website, but captures what I want to have

https://github.com/user-attachments/assets/7a8ab6e4-061f-4375-bc7f-3c3fd14e0696

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment] 2024-12-29 04:02
duplicate of #206

**Closed by Alexander5015** 2024-12-29 04:02 UTC
Labels: duplicate
