### ISSUE TITLE
[BUG]**when I pause my music in the Dynamic Island or in general it appears to keep playing, when it's in fact paused. When I do press play again it goes back to the place where I paused.** **1. go to Dynamic Island 2. click on pause 3. it pauses but the player keeps running.** **the play bar should stay paused at the place it was paused and appear so till play is pressed**

### ISSUE THREAD

**Issue by t0mpoes** [TheBoredTeam/boring.notch#243] opened 2024-12-15 17:10 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or recordings**

**Additional context**
Add any other context about the problem here. Mentioning what version are you using.

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment] 2024-12-16 08:20
Duplicate of #240

**Closed by Alexander5015** 2024-12-16 08:20 UTC
