### ISSUE TITLE
[FEATURE] persistent screen assignment

### ISSUE THREAD

**Issue by userandrewdrew** [TheBoredTeam/boring.notch#267] opened 2024-12-28 10:54 UTC
Is your feature request related to a problem? Please describe.
When using multiple monitors, I often select which screen the notch should appear on. While the feature initially works well it keeps resetting after some time. This results in the notch reverting to the external monitor instead of staying on the monitor I have chosen

Describe the solution you’d like
I would like the application to save the selected monitor for the notch permanently. Once I choose a monitor for the notch, it should remain on that monitor until I explicitly change it in the settings, even after extended use or restarting the application.

**Comment by Alexander5015** [comment] 2024-12-29 04:01
Duplicate of #158 and #247

**Closed by Alexander5015** 2024-12-29 04:01 UTC
Labels: duplicate
