### ISSUE TITLE
[BUG] Sneak Peek Broken

### ISSUE THREAD

**Issue by SgtSalmon** [TheBoredTeam/boring.notch#231] opened 2024-11-30 18:57 UTC
When I change songs on Apple Music, sneak peek doesn't show the name of the song.

https://github.com/user-attachments/assets/6649bac5-ee7a-4fab-a056-895d7d7d5c0d

As shown in the recording, it only shows the name when I pause, then play a song. When changing a song, it does nothing.

I tried to do some troubleshooting. At first, I thought it had to do with Music's crossfade option, but the behavior did not change.

**Comment by Alexander5015** [comment] 2024-11-30 19:27
Duplicate of #211. This has been fixed by #217, and will be released in our next update. You can also try it by building the `dev` branch.

**Closed** 2024-11-30 19:27 UTC
Labels: duplicate
