### ISSUE TITLE
[BUG] External Monitor shows notch midscreen when wakeup Macbook and turning on Monitor

### ISSUE THREAD

**Issue by ibisibisibis** [TheBoredTeam/boring.notch#241] opened 2024-12-11 18:56 UTC
**Describe the bug**
External Monitor shows notch midscreen when wakeup Macbook and turning on Monitor

**To Reproduce**
Send Macbook to Sleep. Turn Monitor off and then wake up both devices

**Comment by Alexander5015** [comment] 2024-12-11 19:27
Duplicate of #219

**Closed** 2024-12-11 19:28 UTC
Labels: duplicate
