### ISSUE TITLE
[BUG] Notch is drawing over text and is hiding it.

### ISSUE THREAD

**Issue by shreyayyyansh** [TheBoredTeam/boring.notch#244] opened 2024-12-16 14:39 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'WPS Office'
2. Open any PDF.
3. Play any media.

**Expected behavior**
It should have adjusted the options(text) so that everything is nice, tidy and clean.

**Screenshots or recordings**
<img width="377" alt="Screenshot 2024-12-16 at 8 02 48 PM" src="https://github.com/user-attachments/assets/ea70fb11-fae1-4867-b028-895d43694d4d" />

**Additional context**
I'm on the latest GlowingPanda version.

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment] 2024-12-16 23:29
Duplicate of #121

**Closed by Alexander5015** 2024-12-16 23:29 UTC
Labels: duplicate
