### ISSUE TITLE
[BUG] Notch shows up in wrong place when connected to monitor

### ISSUE THREAD

**Issue by gavin-ho1** [TheBoredTeam/boring.notch#228] opened 2024-11-26 18:03 UTC
**Describe the bug**
Boring Notch is in incorrect location when switching to monitor/doesn't show up entirely.

**To Reproduce**
1. Plug computer into a monitor and black notch will be in the middle of the screen.
2. Similar thing happens when monitor is disconnected

**Expected behavior**
Notch should show up at top of screen.

**Additional context**
Not sure why this doesn't work. It seemed to have no problem with this in the previous version (2.2)
You can manually fix this issue by restarting Boring Notch after plugging in/unplugging from monitor, but its just very annoying and anyone who doesn't know this is likely to be very confused.

**Comment by Alexander5015** [comment] 2024-11-28 01:01
Duplicate of #219

**Closed by Alexander5015** 2024-11-28 01:01 UTC
Labels: duplicate
