### ISSUE TITLE
[BUG] Notch floating in middle of screen after connecting external display

### ISSUE THREAD

**Issue by liamdmcgarrigle** [TheBoredTeam/boring.notch#250] opened 2024-12-19 00:11 UTC
**Describe the bug**
When connecting to an external display (in this case, in clamshell mode through a thunderbolt dock on an ultra wide monitor)

**To Reproduce**
1. use laptop as normal
2. connect to external display with larger resolution

**Expected behavior**
I expected the notch to scale automatically with the screen and go to the menu bar

**Screenshots or recordings**
↓ Screen cap ↓
https://github.com/user-attachments/assets/6c9aec6a-7833-4ddf-8194-3a38465e59b3

![Screenshot 2024-12-18 at 7 08 46 PM](https://github.com/user-attachments/assets/8d9f4c56-61c5-4f4c-b668-0068dcea63c1)

**Additional context**
- Am using through razer thunderbolt 4 dock
- display is through a usbc displayport cable
- display is an [ultrawide monitor](https://www.amazon.com/gp/product/B07L9HCJ2V)
- non notch display height is set to match menubar height

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment] 2024-12-19 19:42
Duplicate of #219

**Closed by Alexander5015** 2024-12-19 19:42 UTC
